apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tools
spec:
  template:
    spec:
      containers:
        - name: k8s-tools
          image: heysarver/k8s-tools:latest
          imagePullPolicy: Always
